release:
  footer: |
    ## Docker Images
    - `paskalmaksim/telegram-gateway:latest`
    - `paskalmaksim/telegram-gateway:{{ .Tag }}`
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - paskalmaksim/telegram-gateway:latest
  - paskalmaksim/telegram-gateway:{{ .Tag }}
builds:
- dir: ./cmd
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -X main.gitVersion={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'