project_name: telegram-gateway
release:
  footer: |
    ## Docker Images
    - `paskalmaksim/{{.ProjectName}}:latest`
    - `paskalmaksim/{{.ProjectName}}:{{.Version}}`
docker_manifests:
- name_template: paskalmaksim/{{.ProjectName}}:latest
  image_templates:
  - paskalmaksim/{{.ProjectName}}:{{.Version}}-amd64
  - paskalmaksim/{{.ProjectName}}:{{.Version}}-arm64
- name_template: paskalmaksim/{{.ProjectName}}:{{.Version}}
  image_templates:
  - paskalmaksim/{{.ProjectName}}:{{.Version}}-amd64
  - paskalmaksim/{{.ProjectName}}:{{.Version}}-arm64
dockers:
- use: buildx
  goos: linux
  goarch: amd64
  image_templates:
  - paskalmaksim/{{.ProjectName}}:{{.Version}}-amd64
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- use: buildx
  goos: linux
  goarch: arm64
  image_templates:
  - paskalmaksim/{{.ProjectName}}:{{.Version}}-arm64
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
builds:
- dir: ./cmd
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -w -s -X main.gitVersion={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'