apiVersion: v2
icon: https://helm.sh/img/helm.svg
name: telegram-gateway
version: 1.0.6
description: Telegram gateway for Prometheus and Sentry
maintainers:
- name: maksim-paskal  # Maksim Paskal
  email: paskal.maksim@gmail.com
